### ISSUE TITLE
GetVehicleType() returns wrong vehicle type when car transforms in the beginning of a map

### ISSUE THREAD

**Issue by CodyNinja1** [openplanet-nl/vehiclestate#19] opened 2024-07-07 19:48 UTC
![image](https://github.com/openplanet-nl/vehiclestate/assets/82186696/bbc6c531-ed1f-43b9-8f94-888f1e72449c)
Map above is DesertOnRoad in the Desert Discovery.

**Comment by codecat** [comment] 2024-07-07 19:48
Duplicate of #18

**Closed as not planned by codecat** 2024-07-07 19:48 UTC
